name = "MyAstroUtils"
uuid = "e2d25571-835e-4748-919c-7dd32f5092b3"
authors = ["Giorgio Calderone <giorgio.calderone@gmail.com>"]
version = "0.1.0"

[deps]
AstroLib = "c7932e45-9af1-51e7-9da9-f004cd3a462b"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
Healpix = "9f4e344d-96bc-545a-84a3-ae6b9e1b672b"
MySQL = "39abe10b-433b-5dbd-92d4-e302a9df00cd"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SkyCoords = "fc659fc5-75a3-5475-a2ea-3da92c065361"
SortMerge = "041a2d23-8c6e-5597-be73-bf96b5e0dfd4"
StructC14N = "d2514e9c-36c4-5b8e-97e2-51e7675c221c"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAstro = "6112ee07-acf9-5e0f-b108-d242c714bf9f"
WCS = "15f3aee2-9e10-537f-b834-a6fb8bdb944d"
